### PR TITLE
Standalone d3 v7 version

### PR DESCRIPTION
**Pull request by JulesBlm**
This PR updates and refactors the code to work with version of v7 d3. It's also a pretty big refactor that – in my view – simplifies the code. See demo.html for a working example.

It bundles the d3 dependencies along with it using [microbundle](https://github.com/developit/microbundle) for a relatively painless bundling experience. I'm thinking these need not be bundled per sé. Not sure, bundling confuses me.

### CODE REVIEW

**Comment by JulesBlm** [comment]
Forgot to mention, it also includes some updates to the ICS data, the new subdivision of the Holocene

**Comment by smithGit** [comment]
Congratulations, Jules!  This is a very nice contribution to geological time visualization.  I look forward to including it in a project I am working on.  Sam - Michigan

**Comment by davenquinn** [comment]
Hi @JulesBlm, this is a great PR! Do you think that you could shift the version to `2.0.0`, just as a reminder that a previous version exists? Also, it could be good to change the package ID to something like `@macrostrat/geo-timescale` or `@macrostrat/d3-timescale` if you were willing — then I could go ahead and publish using our github org.

**Comment by JulesBlm** [comment]
Ok, I named it "@macrostrat/d3-timescale" to prevent confusion with Macrostrats other [React-based geotimescale](https://github.com/UW-Macrostrat/timescale) and bumped the version number. Feel free to publish it to NPM using the Macrostrat org.

I improved the tick positioning a bit and exposed the currently focused root and it's ancestors names as properties of the `geoTimescale` function, similar the Observable notebook.
One bug that remains that I have not been able to solve so far is that the top two rectangles disappear when the Holocene is focused.

**Comment by smithGit** [comment]
Very cool, Jules.  Daven - hope this is all ok with you and the Macrostrat team.

**Comment by davenquinn** [comment]
Yep, we are happy to have these excellent contributions, and excited to have @JulesBlm as a maintainer here.

I will likely package up the current version as `@macrostrat/d3-timescale` v1 — if we need to grab the code for that, we can just install it from NPM. Then this rewrite can become version 2 on NPM.

As I make progress towards releasing the aforementioned React module, I may ask for your input on the API, @JulesBlm, if you're willing to give it!

**Comment by smithGit** [comment]
Note also: This woud be a great time to compile "the standard" ICS Interval Table - in CVS format as the reference document, with the D3-stratified JSON hierarchy readily derived from that reference.  I do not think such a resource exists -- there are multiple instances but is any one regarded as the "gold standard"?  Also: the semantic web community could benefit if there was a method to harmonize this CVS reference with Wikidata.  Currently Wikidata has stuff that is informal and/or not really official.  
Jules' reference has 172 entries (are the terms "Stage 1, 2, ..." still used?); Wikidata has 268 terms of which 69 are not in Jules list.  SPARQL to get Wikidata is on query.wikidata.org:
## Geological Interval Names in Wikidata
SELECT ?item ?itemLabel ?itemDescription
WHERE 
{
  ?item wdt:P31/wdt:P279* wd:Q4005761. # 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". } # Helps get the label in your language, if not, then en language
}

**Comment by JulesBlm** [comment]
I've posted a question about the disappearing parents when clicking the Holocene node on the Observable forum: [Clicking last node of Icicle leads to incorrect widths in top levels](https://talk.observablehq.com/t/clicking-last-node-of-icicle-leads-to-incorrect-widths-in-top-levels/5597) and it was suggested by user 'mootari' that it might be due to precision problems. When the transition is slowed down – as suggested by mootari – the "Geologic Time" label noticeably starts shaking when clicking shorter nodes (f.e. Late Pleistocene) and in the case of Holocene and child intervals, the parent rectangles disappear. Still not totally sure what causes it. I'll open a new issue for it 

Other than that, everything works fine and I think this is ready to be merged and published to npm. What do you think @davenquinn?

**Comment by smithGit** [comment]
Just a comment:  This is a great visualizaiton of the Geological Time Intervals that I think will ge the attention of geologists and those interested in geology outside the coder world.  Therefore, I suggest holding off publishing into NPM until the tricky issue of the parent intervals disappearing is resolved, with the objective of an actual "release" of a versioned copy of the code maybe the first week of October, with the following objectives:
1. a standalone version on Github
2. an Observable version on Observable, with a name reflecting support or "ownership" by the Macrostrat team at U Wisconsin.  
Thanks to Jules, Daven at Macrostat and also Mootari in the Observable Forum for your help.  This can be not only a Github/Observable resource but a resource that can be used by a wide range of people interested in geology.  Note that these developments are of interest to the International Commission on Stratigraphy.

**Comment by JulesBlm** [comment]
I really don't know how to fix that Holocene parent interval bug and I don't think it will be fixed soon. I'll try posting a question on StackOverflow and see if that get's me anywhere. I also don't think it's a critical bug so I'm fine with merging and publishing it to NPM. If the bug is fixed we just publish a new minor version with the fix.

> As I make progress towards releasing the aforementioned React module, I may ask for your input on the API, @JulesBlm, if you're willing to give it!

Sure, I'd be willing to take a look and provide input if requested @davenquinn.

**Comment by JulesBlm** [comment]
One more thing @davenquinn , could you publish the new version to npm?

**Comment by davenquinn** [comment]
Done! sorry for the delay, GSA got in the way. If you are interested, I can see about giving you publish privileges on NPM.

**Comment by smithGit** [comment]
Daven and Jules:  Thank you very much for the release to NPM.  I am using the code in my history project test site at:  https://hexploredev.azurewebsites.net/#/prj_c301_DeepTime (See buttons for descriptions - let me know if you object to anything there)

With default 960x500 the rows appear not right on my browser; so I am using 960x280 and suggest this as default if others see anomalies in the row heights.

RE: The anomaly where Holocene selection causes top two layers not to display I am using the following work-around (not a good solution) - to force x0 to an arbitrary working value:

      let myX0 =
        leftNeighbor + ((d.x0 - focus.x0) / focusWidth) * widthMinusNeighbors;
      if (
        focus.data.name === "Holocene" &&
        (d.data.name === "Phanerozoic" || d.data.name === "Geologic Time")
      ) {
        // set x0 value to someting that works ok
        myX0 = -75000;
      }
      const target = {
        x0: myX0,

**Pull request merged**
