### PR TITLE
d3 v5 version w concurrent animations

### PR DESCRIPTION
**Pull request by JulesBlm**
I've updated it to work with d3.js version and made the transition animations concurrent. Due to the way the new d3.hierarchy partition function works (see https://github.com/d3/d3-hierarchy#partition) the 'interval_hash" no longer works like it's supposed to. This also makes it hard to easily jump to time period.

Arguably the "goTo" function code has become uglier, repeating to parts to calculate the label's x-positions, but it's the only way I got the transitions to be concurrent.

### CODE REVIEW

**Comment by JulesBlm** [comment]
[Check this bl.ock for a live demo](http://bl.ocks.org/JulesBlm/raw/a25026573de31ea91a2a779d3366929b/)

**Comment by davenquinn** [comment]
Hi @JulesBlm! I just noticed this PR thanks to your prompting.

I have not worked with this code much and am generally happy to have you make updates, but this timescale is used in several active Macrostrat projects and is currently not bundled or updated in a way that gives me confidence that we won't break those integrations if we update the plugin.

I'll have to check the [PBDB Navigator](https://paleobiodb.org/navigator/) in particular to see whether it pulls this code in a "live" way that may potentially be broken if we make changes. If that's not the case, I'm happy to make you maintainer. Any input @jczaplew, as the original author here?

If we merge this PR, I'd like to also make it bundle the JS appropriately for NPM install.

By the way, I'm working on a new project for React-based timescales, UW-Macrostrat/timescale, (see [in use](https://dev.macrostrat.org/next/ui-concepts/multiscale-figure/index.html)) that may supersede this project for some use cases.

**Comment by davenquinn** [comment]
OK, I just checked the PBDB Navigator code (highest profile project I know of that uses this or something similar) and it seems like it's not directly referencing this code. So I think we might be in the clear to apply some updates, a fix to #3 being the highest priority. Happy to make you maintainer if so @JulesBlm.

Let's wait a bit to see if @jczaplew chimes in. But otherwise, all set.

**Comment by JulesBlm** [comment]
Great, yes I’d like to become a maintainer. I’ll start looking into updating it d3 v6 or v7 sometime next week. That UW-Macrostrat/timescale demo looks amazing btw

**Comment by JulesBlm** [comment]
I've made a new pull request for the update to v7 as the code differs greatly from the code in this pull request. See https://github.com/UW-Macrostrat/geo-timescale/pull/6.

**Comment by JulesBlm** [comment]
Also, in that case, could I be made a maintainer of this repository?

**Comment by JulesBlm** [comment]
Closed, superseded by https://github.com/UW-Macrostrat/geo-timescale/pull/6

**Pull request closed without merging**
